# Generated by Django 5.2.6 on 2026-01-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_notification_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_table',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
