# Generated by Django 5.2.6 on 2026-02-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rating_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_table',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
